/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xbCmLn7yri0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client";
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useState } from "react";

export default function Home() {
  const [text, setText] = useState<string>("");
  return (
    <div className="max-w-3xl mx-auto grid gap-4">
      <div className="rounded-lg border border-gray-200 grid gap-4 p-4 dark:border-gray-800">
        <div className="space-y-2">
          <Label className="text-lg" htmlFor="text">
            Enter your text
          </Label>
          <Textarea className="min-h-[200px]" id="text" placeholder="Enter your text here." value={text} onChange={(e)=>{setText(e.target.value)}}/>
        </div>
        <div className="flex justify-center">
          <Button onSubmit={()=>{}}>Generate</Button>
        </div>
      </div>
      <div className="grid gap-4">
        <div className="rounded-lg border border-gray-200 p-4 flex items-center justify-center dark:border-gray-800">
          <span className="w-full max-w-full aspect-video rounded-md bg-gray-100 dark:bg-gray-800" />
        </div>
        <Button className="w-full">Download video</Button>
      </div>
    </div>
  )
}
